=== evmos/chain-token-registry/schema.token.json
{
  "$id": "https://evmos.org/schema.token.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "Token Schema Registry via Evmos Governance",
  "type": "object",
  "properties": {
    "coinDenom": {
      "type": "string",
      "description": "Coin denom representation, i.e BTC "
    },
    "minCoinDenom": {
      "type": "string",
      "description": "Minimal coin denom, i.e. satoshi for Bitcoin"
    },
    "imgSrc": {
      "type": "string",
      "description": "Link must be SVG link only. If this image is coming from Github, make sure it has a pattern of 'https://raw.githubusercontent.com/cosmos/chain-registry/master/${chain}/images/${coin}.svg' and the link directly opens the image only and not the site of Github with the image."
    },
    "pngSrc": {
      "type": "string",
      "description": "Link must be png source. If this image is coming from Github, make sure it has a pattern of 'https://raw.githubusercontent.com/cosmos/chain-registry/master/${chain}/images/${coin}.png' and the link directly opens the image only and not the site of Github with the image."
    },
    "type": {
      "type": "string",
      "enum": ["IBC", "ERC-20", "CW20"]
    },
    "exponent": {
      "type": "string"
    },
    "cosmosDenom": {
      "type": "string",
      "description": "Starting with ibc/..."
    },
    "description": {
      "type": "string",
      "description": "Coin description goes here. This description will be used to describe the coin to the user. Please keep it concise."
    },
    "name": {
      "type": "string",
      "description": "Official name of the coin, i.e. EVMOS"
    },
    "tokenRepresentation": {
      "type": "string",
      "description": "Single token representation,i.e. EVMOS, it's the grouping key for the assets page"
    },
    "channel": {
      "type": "string",
      "description": "Channel must be active. Check https://www.mintscan.io/evmos/relayers and find the right network to see which channel is open on both ends. The value wanted here is the From side of Evmos."
    },
    "isEnabled": {
      "type": "boolean",
      "default": true,
      "description": "Default to true"
    },
    "erc20Address": {
      "type": "string",
      "description": "Hex address only, i.e. 0x. Can be found on the Evmos API TokenPairs endpoint. This field will be populated when the token passes governance."
    },
    "ibc": {
      "type": "object",
      "properties": {
        "sourceDenom": {
          "type": "string",
          "description": "There are two states for sourceDenom. Main chain coins like EVMOS will have their minCoinDenom listed here, however, coins from that ecosystem other than the main coin will require its prefix+hexAddress, i.e. gravity0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48 for Gravity's USDC.grv"
        },
        "source": {
          "type": "string",
          "description": "Chain name, i.e. Cosmos or Osmosis"
        }
      }
    },
    "hideFromTestnet": {
      "type": "boolean",
      "default": false,
      "description": "If network does not have testnet and the coin is not in the testnet via governance or other means, mark this as true, otherwise, leave as is."
    },
    "coingeckoId": {
      "type": "string",
      "description": "Official string coingecko uses to search and load the asset. Please insure the text matches exactly."
    },
    "category": {
      "type": "string",
      "description": "Select a parental category of this asset. If a category does not exist, please feel free to create a PR to update the schema. For example, all wrapped token are part of the parent category, gWBTC is 'bitcoin'.",
      "default": "none",
      "enum": ["bitcoin", "ethereum", "stablecoin", "cosmos", "polygon", "none"]
    },
    "coinSourcePrefix": {
      "type": "string",
      "description": "Use this field to declare if the coin is part of a network's ecosystem, like for example, gWBTC is part of Gravity. If the coin is the main network coin, then the response will be itself still. the string here should match the network prefix."
    },
    "handledByExternalUI": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["url", "handlingAction"],
        "properties": {
          "url": {
            "type": "string",
            "description": "Link to the external UI site"
          },
          "handlingAction": {
            "type": "string",
            "enum": [
              "Deposit",
              "Withdraw",
              "Convert",
              "Deposit and Withdraw",
              "All"
            ],
            "description": "Specify if the external UI is for Deposit, Withdraw, Convert, or others."
          }
        }
      }
    }
  },
  "required": [
    "coinDenom",
    "minCoinDenom",
    "pngSrc",
    "type",
    "exponent",
    "cosmosDenom",
    "description",
    "name",
    "tokenRepresentation",
    "channel",
    "erc20Address",
    "ibc",
    "coingeckoId",
    "coinSourcePrefix",
    "category"
  ]
}

=== evmos/chain-token-registry/tokens/CMST.json
{
  "coinDenom": "CMST",
  "minCoinDenom": "ucmst",
  "imgSrc": "https://raw.githubusercontent.com/cosmos/chain-registry/master/comdex/images/cmst.svg",
  "pngSrc": "https://raw.githubusercontent.com/cosmos/chain-registry/master/comdex/images/cmst.png",
  "type": "IBC",
  "exponent": "6",
  "cosmosDenom": "ibc/9EC8A1701813BB7B73BFED2496009ABB2C8BF187E6CDFA788D77F68E08BC05CD",
  "description": "An over-collateralized soft-pegged token to the USD on the Comdex chain",
  "name": "CMST Stablecoin of Harbor protocol",
  "tokenRepresentation": "CMST",
  "channel": "channel-26",
  "isEnabled": true,
  "erc20Address": "0x9d6F2a9fDB32708e1AC07788cc29D6125ac73027",
  "ibc": {
    "sourceDenom": "ucmst",
    "source": "Comdex"
  },
  "hideFromTestnet": false,
  "coingeckoId": "composite",
  "category": "stablecoin",
  "coinSourcePrefix": "comdex"
}

=== evmos/chain-token-registry/tokens/QCK.json
{
  "coinDenom": "QCK",
  "minCoinDenom": "uqck",
  "imgSrc": "https://raw.githubusercontent.com/cosmos/chain-registry/master/quicksilver/images/qck.svg",
  "pngSrc": "https://raw.githubusercontent.com/cosmos/chain-registry/master/quicksilver/images/qck.png",
  "type": "IBC",
  "exponent": "6",
  "cosmosDenom": "ibc/FCA18B0C0D1236E203D1AE09634A3F33E8AC31707CD59A74A437A903231C653C",
  "description": "QCK - native token of Quicksilver",
  "name": "Quicksilver",
  "tokenRepresentation": "QCK",
  "channel": "channel-37",
  "isEnabled": true,
  "erc20Address": "0xf55454383cEEFB1B5e889E59542352B1b928707d",
  "ibc": {
    "sourceDenom": "uqck",
    "source": "Quicksilver"
  },
  "hideFromTestnet": false,
  "coingeckoId": "quicksilver",
  "category": "cosmos",
  "coinSourcePrefix": "quick"
}

=== evmos/chain-token-registry/tokens/stEVMOS.json
{
    "coinDenom": "stEVMOS",
    "minCoinDenom": "staevmos",
    "imgSrc": "https://raw.githubusercontent.com/cosmos/chain-registry/master/stride/images/stevmos.svg",
    "pngSrc": "https://raw.githubusercontent.com/cosmos/chain-registry/master/stride/images/stevmos.png",
    "type": "IBC",
    "exponent": "18",
    "cosmosDenom": "ibc/C49FDA9CB980D813492E2DFFF255B01C46E629C73B2B468131F6FE6E14F55754",
    "description": "Staking derivative by Stride",
    "name": "Stride Staked Evmos",
    "tokenRepresentation": "EVMOS",
    "channel": "channel-25",
    "isEnabled": true,
    "erc20Address": "0x2C68D1d6aB986Ff4640b51e1F14C716a076E44C4",
    "ibc": {
      "sourceDenom": "staevmos",
      "source": "Stride"
    },
    "hideFromTestnet": false,
    "coingeckoId": "stride-staked-evmos",
    "category": "cosmos",
    "coinSourcePrefix": "stride"
  }

=== evmos/chain-token-registry/tokens/INJ.json
{
  "coinDenom": "INJ",
  "minCoinDenom": "inj",
  "imgSrc": "",
  "pngSrc": "https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/images/inj.png",
  "type": "IBC",
  "exponent": "18",
  "cosmosDenom": "ibc/ADF401C952ADD9EE232D52C8303B8BE17FE7953C8D420F20769AF77240BD0C58",
  "description": "The INJ token is the native governance token for the Injective chain.",
  "name": "Injective",
  "tokenRepresentation": "INJ",
  "channel": "channel-10",
  "isEnabled": true,
  "erc20Address": "0x3515F25AB7637adcF1b69F4D384ed5936B83431F",
  "ibc": {
    "sourceDenom": "inj",
    "source": "Injective"
  },
  "hideFromTestnet": false,
  "coingeckoId": "injective-protocol",
  "category": "cosmos",
  "coinSourcePrefix": "inj"
}

=== evmos/chain-token-registry/tokens/USDT.json
{
    "coinDenom": "USDT",
    "minCoinDenom": "erc20/tether/usdt",
    "imgSrc": "https://assets.coingecko.com/coins/images/325/small/Tether.png",
    "pngSrc": "https://assets.coingecko.com/coins/images/325/small/Tether.png",
    "type": "IBC",
    "exponent": "6",
    "cosmosDenom": "ibc/95F4898F70B1E3765715808C57E955034419200A7BB6DDECBEAA5FD3AA3DF7D5",
    "description": "Native USDT issued on Kava",
    "name": "USDT on Kava",
    "tokenRepresentation": "USDT",
    "channel": "channel-83",
    "isEnabled": true,
    "erc20Address": "0xB8f812B5943ab3BF941D5D4F1de90A4b326c5d8f",
    "ibc": {
      "sourceDenom": "erc20/tether/usdt",
      "source": "Kava"
    },
    "hideFromTestnet": false,
    "coingeckoId": "tether",
    "category": "stablecoin",
    "coinSourcePrefix": "kava"
  }

=== evmos/chain-token-registry/tokens/AXL.json
{
  "coinDenom": "AXL",
  "minCoinDenom": "uaxl",
  "imgSrc": "https://raw.githubusercontent.com/cosmos/chain-registry/master/axelar/images/axl.svg",
  "pngSrc": "https://raw.githubusercontent.com/cosmos/chain-registry/master/axelar/images/axl.png",
  "type": "IBC",
  "exponent": "6",
  "cosmosDenom": "ibc/473351B37CC9D7BA7B247800EF04D255E442C4C9C93976E3631B190A8F3C5570",
  "description": "The native token of Axelar",
  "name": "Axelar",
  "tokenRepresentation": "AXL",
  "channel": "channel-21",
  "isEnabled": true,
  "erc20Address": "0x94c23eE865E3c963A56263d0ce2CBF5C6cE7ce2d",
  "ibc": {
    "sourceDenom": "uaxl",
    "source": "Axelar"
  },
  "hideFromTestnet": false,
  "coingeckoId": "axelar",
  "category": "cosmos",
  "coinSourcePrefix": "axelar"
}

=== evmos/chain-token-registry/tokens/axlDAI.json
{
  "coinDenom": "axlDAI",
  "minCoinDenom": "dai-wei",
  "imgSrc": "https://raw.githubusercontent.com/cosmos/chain-registry/master/axelar/images/axldai.svg",
  "pngSrc": "https://raw.githubusercontent.com/cosmos/chain-registry/master/axelar/images/axldai.png",
  "type": "IBC",
  "exponent": "18",
  "cosmosDenom": "ibc/CBA4784581AD4BEF308C536A3CD44D4A940A520E61B0D1E4FB115C539F61DEE5",
  "description": "DAI Stablecoin on Axelar",
  "name": "DAI by Axelar",
  "tokenRepresentation": "DAI",
  "channel": "channel-21",
  "isEnabled": true,
  "erc20Address": "0x4A2a90D444DbB7163B5861b772f882BbA394Ca67",
  "ibc": {
    "sourceDenom": "axldai",
    "source": "Axelar"
  },
  "hideFromTestnet": true,
  "handledByExternalUI": [
    {
      "url": "https://satellite.money/",
      "handlingAction": "Deposit and Withdraw"
    }
  ],
  "coingeckoId": "dai",
  "category": "stablecoin",
  "coinSourcePrefix": "axelar"
}

=== evmos/chain-token-registry/tokens/stJUNO.json
{
  "coinDenom": "stJUNO",
  "minCoinDenom": "stujuno",
  "imgSrc": "https://raw.githubusercontent.com/cosmos/chain-registry/master/stride/images/stjuno.svg",
  "pngSrc": "https://raw.githubusercontent.com/cosmos/chain-registry/master/stride/images/stjuno.png",
  "type": "IBC",
  "exponent": "6",
  "cosmosDenom": "ibc/D9C9DFD2B4021D16B01AC16ECD5A7933383C38F8331160583E0A5F34B30E1BA9",
  "description": "Staking derivative by Stride",
  "name": "Stride Staked Juno",
  "tokenRepresentation": "JUNO",
  "channel": "channel-25",
  "isEnabled": true,
  "erc20Address": "0xc71aAf8e486e3F33841BB56Ca3FD2aC3fa8D29a8",
  "ibc": {
    "sourceDenom": "stujuno",
    "source": "Stride"
  },
  "hideFromTestnet": false,
  "coingeckoId": "stride-staked-juno",
  "category": "cosmos",
  "coinSourcePrefix": "stride"
}
