=== evmos/chain-token-registry/schema.chain.json
{
  "$id": "https://evmos.org/schema.token.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "Chain Registry via Evmos Governance",
  "type": "object",
  "required": ["gasPriceStep", "prefix", "bip44", "configurations"],
  "properties": {
    "prefix": {
      "type": "string",
      "description": "Chain prefix i.e. evmos. This is the field whereby all the address will start off (i.e. evmos1ffttr...)"
    },
    "gasPriceStep": {
      "type": "object",
      "required": ["low", "average", "high"],
      "properties": {
        "low": {
          "type": "string",
          "description": "Amount of gas for Low"
        },
        "average": {
          "type": "string",
          "description": "Amount of gas for Average"
        },
        "high": {
          "type": "string",
          "description": "Amount of gas for High"
        }
      }
    },
    "feeMarket": {
      "type": "object",
      "description": "Only applicable to EVMOS",
      "required": ["gas", "amount", "convert"],
      "properties": {
        "gas": {
          "type": "string",
          "description": "Enter appropriate gas cost"
        },
        "amount": {
          "type": "string",
          "description": "Enter appropriate amount cost"
        },
        "convert": {
          "type": "string",
          "description": "Enter appropriate convert cost"
        }
      }
    },
    "bip44": {
      "type": "object",
      "required": ["coinType"],
      "properties": {
        "coinType": {
          "type": "string",
          "description": "Cosmos-based chains should be 118 while EVM-based chains are coin type 60. If you are entering a coinType that is not 60 or 118, please reach out, we love to chat."
        }
      }
    },
    "configurations": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "chainId",
          "identifier",
          "chainName",
          "clientId",
          "rest",
          "rpc",
          "currencies",
          "source",
          "configurationType",
          "img"
        ],
        "properties": {
          "chainId": {
            "type": "string",
            "description": "Chain ID should specific to the environment, i.e. Testnet and Mainnet are different"
          },
          "identifier": {
            "type": "string",
            "description": "Global identifier to be used by both client and backend as default reference for the chain"
          },
          "img": {
            "type": "object",
            "required": ["png"],
            "properties": {
              "png": {
                "type": "string",
                "description": "Link to the chain logo",
                "pattern": "^https://raw\\.githubusercontent\\.com/evmos/chain-token-registry/main/assets/chainConfig/.+\\.png$"
              },
              "svg": {
                "type": "string",
                "description": "Link to the chain logo",
                "pattern": "^https://raw\\.githubusercontent\\.com/evmos/chain-token-registry/main/assets/chainConfig/.+\\.svg$"
              }
            }
          },
          "chainName": {
            "type": "string",
            "description": "Name of the chain specific to the environment, i.e. Evmos Testnet"
          },
          "clientId": {
            "type": "string",
            "description": "Query the 'evmosd query ibc channel client-state [port-id] [channel-id] [flags]' and copy over the client-id field"
          },
          "rpc": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "RPC endpoint link, usually port 1317"
          },
          "rest": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 2,
            "uniqueItems": true
          },
          "jrpc": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "minItems": 2,
            "uniqueItems": true
          },
          "web3": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "currencies": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "coinDenom": {
                  "type": "string",
                  "description": "Unit of the coin or symbol, i.e. EVMOS"
                },
                "coinMinDenom": {
                  "type": "string",
                  "description": "Smallest unit of the coin, i.e. aevmos"
                },
                "coinDecimals": {
                  "type": "string",
                  "description": "Chain minimum coin denomination, i.e. aevmos"
                }
              }
            }
          },
          "source": {
            "type": "object",
            "required": [
              "sourceChannel",
              "sourceIBCDenomToEvmos",
              "destinationChannel",
              "jsonRPC"
            ],
            "properties": {
              "sourceChannel": {
                "type": "string",
                "description": "Source channel represents the third-party, i.e. Cosmos Hub side"
              },
              "sourceIBCDenomToEvmos": {
                "type": "string",
                "description": "The value is ibc/[sha256 of 'transfer/${sourceChannel}/aevmos' phrase]. This value is required to pull in EVMOS from source chain to Evmos chain."
              },
              "destinationChannel": {
                "type": "string",
                "description": "Destination channel represents the main network side, i.e. EVMOS side"
              },
              "jsonRPC": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "minItems": 1,
                "description": "Tendermint endpoint link or using port 26657"
              }
            }
          },
          "explorer": {
            "type": "array",
            "description": "Explorer is only necessary for EVMOS network. All other Cosmos chains do not require this array object to be filled out",
            "items": {
              "type": "object",
              "required": ["link", "type"],
              "properties": {
                "type": {
                  "type": "string",
                  "enum": ["evm", "cosmos"],
                  "description": "Add the correct explorer data type"
                },
                "link": {
                  "type": "string",
                  "description": "Link to explorer"
                }
              }
            }
          },
          "cosmosRegistryUrl": {
            "type": "string",
            "description": "Link to the Cosmos Registry"
          },
          "configurationType": {
            "type": "string",
            "enum": ["mainnet", "testnet"],
            "description": "Must select either mainnet or testnet"
          },
          "explorerTxUrl": {
            "type": "string",
            "description": "Explorer tx URL for the chain, i.e https://www.mintscan.io/evmos/txs."
          }
        }
      }
    }
  }
}

=== evmos/chain-token-registry/chainConfig/injective.json
{
  "$schema": "../schema.chain.json",
  "prefix": "inj",
  "gasPriceStep": {
    "low": "100000000000",
    "average": "200000000000",
    "high": "30000000000000"
  },
  "bip44": {
    "coinType": "60"
  },
  "configurations": [
    {
      "chainId": "injective-1",
      "chainName": "Injective",
      "identifier": "injective",
      "clientId": "07-tendermint-19",
      "rest": [
        "https://lcd.injective.network",
        "https://injective-api.polkachu.com",
        "https://injective-api.lavenderfive.com:443"
      ],
      "jrpc": [
        "https://tm.injective.network",
        "https://injective-rpc.polkachu.com",
        "https://injective-rpc.quickapi.com:443"
      ],
      "rpc": ["https://tm.injective.network"],
      "currencies": [
        {
          "coinDenom": "INJ",
          "coinMinDenom": "inj",
          "coinDecimals": "18"
        }
      ],
      "source": {
        "sourceChannel": "channel-83",
        "sourceIBCDenomToEvmos": "ibc/16618B7F7AC551F48C057A13F4CA5503693FBFF507719A85BC6876B8BD75F821",
        "destinationChannel": "channel-10",
        "jsonRPC": ["https://tm.injective.network"]
      },
      "configurationType": "mainnet",
      "explorerTxUrl": "https://www.mintscan.io/injective/txs",
      "img": {
        "svg": "https://raw.githubusercontent.com/evmos/chain-token-registry/main/assets/chainConfig/injective.svg",
        "png": "https://raw.githubusercontent.com/evmos/chain-token-registry/main/assets/chainConfig/injective.png"
      },
      "cosmosRegistryUrl": "https://raw.githubusercontent.com/cosmos/chain-registry/master/injective/chain.json"
    }
  ]
}

=== evmos/chain-token-registry/chainConfig/crescent.json
{
  "$schema": "../schema.chain.json",
  "prefix": "cre",
  "gasPriceStep": {
    "low": "0.01",
    "average": "0.025",
    "high": "0.03"
  },
  "bip44": {
    "coinType": "118"
  },
  "configurations": [
    {
      "chainId": "crescent-1",
      "chainName": "Crescent Network",
      "identifier": "crescent",
      "clientId": "07-tendermint-38",
      "rest": [
        "https://mainnet.crescent.network:1317",
        "https://api-crescent.pupmos.network",
        "https://crescent-api.polkachu.com",
        "https://crescent.rest.stakin-nodes.com",
        "https://crescent-mainnet-lcd.autostake.net:443"
      ],
      "jrpc": [
        "https://mainnet.crescent.network:26657",
        "https://crescent-rpc.polkachu.com",
        "https://rpc-crescent.pupmos.network",
        "https://crescent.rpc.stakin-nodes.com",
        "https://crescent-mainnet-rpc.autostake.net:443"
      ],
      "rpc": [""],
      "currencies": [
        {
          "coinDenom": "CRE",
          "coinMinDenom": "ucre",
          "coinDecimals": "6"
        }
      ],
      "source": {
        "sourceChannel": "channel-7",
        "sourceIBCDenomToEvmos": "ibc/73E97EB411B29C6F989C35D277D1A7FC65083572F102AC6BD101884EE9FB2C9F",
        "destinationChannel": "channel-11",
        "jsonRPC": ["https://mainnet.crescent.network:26657/"]
      },
      "configurationType": "mainnet",
      "explorerTxUrl": "https://www.mintscan.io/crescent/txs",
      "img": {
        "svg": "https://raw.githubusercontent.com/evmos/chain-token-registry/main/assets/chainConfig/crescent.svg",
        "png": "https://raw.githubusercontent.com/evmos/chain-token-registry/main/assets/chainConfig/crescent.png"
      },
      "cosmosRegistryUrl": "https://raw.githubusercontent.com/cosmos/chain-registry/master/crescent/chain.json"
    }
  ]
}

=== evmos/chain-token-registry/chainConfig/wormhole.json
{
  "$schema": "../schema.chain.json",
  "prefix": "wormhole",
  "gasPriceStep": {
    "low": "0",
    "average": "0",
    "high": "0"
  },
  "bip44": {
    "coinType": "118"
  },
  "configurations": [
    {
      "chainId": "wormchain",
      "chainName": "Wormhole Gateway",
      "identifier": "wormhole",
      "rpc": ["https://wormchain-rpc.quickapi.com:443"],
      "rest": [
        "https://wormchain-lcd.quickapi.com",
        "https://tncnt-eu-wormchain-main-01.rpc.p2p.world/lcd"
      ],
      "jrpc": [
        "https://wormchain-rpc.quickapi.com",
        "https://tncnt-eu-wormchain-main-01.rpc.p2p.world",
        "https://wormchain.jumpisolated.com"
      ],
      "clientId": "07-tendermint-119",
      "currencies": [
        {
          "coinDenom": "WORM",
          "coinMinDenom": "uworm",
          "coinDecimals": "6"
        }
      ],
      "source": {
        "sourceChannel": "channel-94",
        "sourceIBCDenomToEvmos": " ",
        "destinationChannel": "channel-5",
        "jsonRPC": ["https://wormchain-rpc.quickapi.com:443"]
      },
      "configurationType": "mainnet",
      "explorerTxUrl": "https://bigdipper.live/wormhole/transactions",
      "img": {
        "svg": "https://raw.githubusercontent.com/evmos/chain-token-registry/main/assets/chainConfig/wormhole.svg",
        "png": "https://raw.githubusercontent.com/evmos/chain-token-registry/main/assets/chainConfig/wormhole.png"
      },
      "cosmosRegistryUrl": "https://raw.githubusercontent.com/cosmos/chain-registry/master/gateway/chain.json"
    }
  ]
}
